package com.lushprojects.circuitjs1.client;

enum GeneratedFaultType {
    RESISTOR_OPEN,
    RESISTOR_INCORRECT_VALUE,
    DIODE_OPEN,
    DIODE_SHORT,
    CAPACITOR_OPEN,
    CAPACITOR_SHORT,
    CONNECTOR_OPEN_PATH,
    TRANSISTOR_CE_OPEN,
    TRANSISTOR_CE_SHORT,
    BASE_RESISTOR_OPEN,
    LOAD_PATH_OPEN,
    NMOS_DS_OPEN,
    NMOS_DS_SHORT,
    NMOS_GATE_OPEN
}
